name: video_player_example
version: 1.0.0+1
publish_to: "none"
description: "Demonstrates how to use the video_player plugin."

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5

flutter:
  uses-material-design: true
