name: video_player
version: 2.1.0
description: "Play video natively and easily."
homepage: https://github.com/SunnatilloShavkatov/video_player.git

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5

flutter:
  plugin:
    platforms:
      android:
        package: uz.shs.video_player
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: VideoPlayerPlugin